-- MySQL Script generated by MySQL Workbench
-- 09/15/14 13:15:28
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zonaamigos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zonaamigos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zonaamigos` ;

-- -----------------------------------------------------
-- Table `zonaamigos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zonaamigos`.`usuarios` (
  `ideusu_usu` INT NOT NULL AUTO_INCREMENT,
  `nombre_usu` VARCHAR(60) NULL,
  `apellido_usu` VARCHAR(60) NULL,
  `telefono_usu` VARCHAR(10) NULL,
  `email_usu` VARCHAR(60) NULL,
  PRIMARY KEY (`ideusu_usu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zonaamigos`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zonaamigos`.`ubicaciones` (
  `ideubi_ubi` INT NOT NULL AUTO_INCREMENT,
  `ideusu_ubi` INT NOT NULL,
  `latitu_ubi` DOUBLE NULL,
  `longit_ubi` DOUBLE NULL,
  `fecha_ubi` DATE NULL,
  `hora_ubi` TIME NULL,
  PRIMARY KEY (`ideubi_ubi`, `ideusu_ubi`),
  INDEX `fk_ubicaciones_usuarios_idx` (`ideusu_ubi` ASC),
  CONSTRAINT `fk_ubicaciones_usuarios`
    FOREIGN KEY (`ideusu_ubi`)
    REFERENCES `zonaamigos`.`usuarios` (`ideusu_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
